### ISSUE TITLE
Signature Spoofing not working correctly

### ISSUE THREAD

**Issue by ghost** [nitrogen-project/android_packages_apps_NitrogenSettings#2]
Your ROM has the ability to enable signature spoofing, but it's not working correctly. I wonder, why microG was not working, but it seems that spoofing is disabled.

Steps to reproduce:

1.  Enable Signature Spoofing in Personalization, Miscellaneous and check "Allow signature spoofing"
2.  Install Sigspoof Checker (https://github.com/Lanchon/sigspoof-checker)
3.  App says Signature spoofing disabled

**Comment by xyyx** [comment]
You are wrong. It works correctly. You need to allow signature spoofing for microG application.
Settings-Apps-Permissions

**Comment by ghost** [comment]
I checked it out, so you'll have to enable spoofing for each app. Thank you, I'll close this issue.
Should'nt the app ask for permission?

**Comment by xyyx** [comment]
No. It's not standart permission. It's hack)

**Comment by ghost** [comment]
Ok, thank you. Thumbs up!
